name: Build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64,linux/arm64
          provenance : "false"
          push: "false"
          # build-args: ${{ inputs.build-args }}
          # context: ${{ inputs.build-context }}
          # file: ${{ inputs.file }}
